name: wow_app_test_task
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  catcher: ^0.6.8
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.3.5
  flutter_svg: ^0.22.0
  get: ^4.3.8
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl_phone_number_input: ^0.7.0+2
  logger: ^1.1.0
  retrofit: ^2.0.1
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  retrofit_generator: ^2.0.1+1

dependency_overrides:
  # conflict between hive_generator && retrofit_generator
  analyzer: ^2.0.0
  meta: ^1.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
